In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

In [2]:
df = pd.read_csv('C:/부동산/data/finaldata_전처리.csv')

In [4]:
df_region = df[df['구'] == '강남구']

In [5]:
df_region.columns

Index(['계약년월일', '전용면적', '거래금액', '층', '건축년도', '면적당가격', '구', '동', '계약년', '계약월',
       '계약일', '년월', '일자', '주택담보대출', '미국달러', '일본엔', '유로', '소비자물가지수',
       '소비자물가지수증감률', 'KOSPI_종가', 'KOSDAQ_종가', '무담보콜금리', 'KORIBOR', 'CD',
       '국고채_1년', '국고채_10년'],
      dtype='object')

In [12]:
X = df_region[['전용면적', '층', '건축년도', '계약년', '계약월',
       '주택담보대출', '미국달러', '일본엔', '유로',
       'KOSPI_종가', 'KOSDAQ_종가', '무담보콜금리', 'KORIBOR', 'CD',
       '국고채_1년', '국고채_10년']]
y = df_region['면적당가격']

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = LinearRegression().fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.4662342431273788
검증용 :  0.4733990498660129


In [17]:
predict = model.predict([[1, 1, 1, 1, 1, 1, 1, 1 ,1, 1, 1 ,1 ,1, 1, 1 ,1]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-337885.14421502])

In [18]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = DecisionTreeRegressor().fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.9982098420737707
검증용 :  0.8348785172416402


In [19]:
predict = model.predict([[1, 1, 1, 1, 1, 1, 1, 1 ,1, 1, 1 ,1 ,1, 1, 1 ,1]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([1768.89592402])

In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = RandomForestRegressor(n_jobs = -1).fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.9854619168411758
검증용 :  0.9041688780555976


In [21]:
predict = model.predict([[1, 1, 1, 1, 1, 1, 1, 1 ,1, 1, 1 ,1 ,1, 1, 1 ,1]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([2115.39743992])